### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by dessant** [comment]
Thanks for your contribution! I'm going to set up a Crowdin project in the near future and import the translated strings there for validation.

**Comment by Elaborendum** [comment]
@dessant Does that mean that we can currently contribute with translations (because they will be later imported to the Crowdin project) or do we wait for the project to be set up?

**Comment by Thanasis-Koligliatis** [comment]
I would like to translate the app in Greek.

Also,
Search by Image for Samsung Internet

You could make it a free trial for a day,
so that people could try it first,
to see how well it actually works.

Because people may be reluctant to pay 5€ for something that they don't really know.

**Comment by dessant** [comment]
Thanks for your contribution, I will include your work if translations will be supported at some point in the future and will notify you. I just don't have the time now to support this feature.

**Pull request closed without merging**
